// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qlthucung.Models;

namespace qlthucung.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("qlthucung.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("qlthucung.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("Madon")
                        .HasColumnType("int")
                        .HasColumnName("madon");

                    b.Property<int>("Masp")
                        .HasColumnType("int")
                        .HasColumnName("masp");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("gia");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("soluong");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal?>("Tonggia")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("tonggia");

                    b.Property<int?>("Tongsoluong")
                        .HasColumnType("int")
                        .HasColumnName("tongsoluong");

                    b.HasKey("Madon", "Masp")
                        .HasName("PK__ChiTietD__3C460110D46F34D2");

                    b.HasIndex("Masp");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("qlthucung.Models.DanhGium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdKh")
                        .HasColumnType("int")
                        .HasColumnName("id_kh");

                    b.Property<int?>("IdSp")
                        .HasColumnType("int")
                        .HasColumnName("id_sp");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("Trangthai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trangthai")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("IdKh");

                    b.HasIndex("IdSp");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("qlthucung.Models.DanhMuc", b =>
                {
                    b.Property<int>("IdDanhmuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDanhmuc")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ParentID");

                    b.Property<string>("Tendanhmuc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tendanhmuc");

                    b.HasKey("IdDanhmuc")
                        .HasName("PK__DanhMuc__DB790BF68C813DE1");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("qlthucung.Models.DichVu", b =>
                {
                    b.Property<int>("Iddichvu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iddichvu")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diachi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("diachi");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("email");

                    b.Property<string>("Hoten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("hoten");

                    b.Property<int?>("Makh")
                        .HasColumnType("int")
                        .HasColumnName("makh");

                    b.Property<DateTime?>("Ngaydat")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaydat");

                    b.Property<string>("Sdt")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("sdt");

                    b.Property<string>("Tendichvu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tendichvu");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("trangthai");

                    b.HasKey("Iddichvu")
                        .HasName("PK__DichVu__77FDDBF8BC48DDF1");

                    b.HasIndex("Makh");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("qlthucung.Models.DonHang", b =>
                {
                    b.Property<int>("Madon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("madon")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Giaohang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("giaohang");

                    b.Property<int?>("Makh")
                        .HasColumnType("int")
                        .HasColumnName("makh");

                    b.Property<DateTime?>("Ngaydat")
                        .HasColumnType("date")
                        .HasColumnName("ngaydat");

                    b.Property<DateTime?>("Ngaygiao")
                        .HasColumnType("date")
                        .HasColumnName("ngaygiao");

                    b.Property<string>("Thanhtoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("thanhtoan");

                    b.HasKey("Madon")
                        .HasName("PK__DonHang__0BE416770A34913A");

                    b.HasIndex("Makh");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("qlthucung.Models.KhachHang", b =>
                {
                    b.Property<int>("Makh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("makh")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diachi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("diachi");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("dienthoai");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hoten");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("matkhau");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("Resetpasswordcode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("resetpasswordcode");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Tendangnhap")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tendangnhap");

                    b.HasKey("Makh")
                        .HasName("PK__KhachHan__7A21BB4CE42C9226");

                    b.HasIndex("RoleId");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("qlthucung.Models.KhachHangRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("RoleId")
                        .HasName("PK__KhachHan__8AFACE3A2B34BEF9");

                    b.ToTable("KhachHangRoles");
                });

            modelBuilder.Entity("qlthucung.Models.SanPham", b =>
                {
                    b.Property<int>("Masp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("masp")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Giaban")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("giaban");

                    b.Property<decimal?>("Giakhuyenmai")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("giakhuyenmai");

                    b.Property<int?>("Giamgia")
                        .HasColumnType("int")
                        .HasColumnName("giamgia");

                    b.Property<string>("Hinh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh");

                    b.Property<int?>("IdDanhmuc")
                        .HasColumnType("int")
                        .HasColumnName("idDanhmuc");

                    b.Property<int?>("Idthuvien")
                        .HasColumnType("int")
                        .HasColumnName("idthuvien");

                    b.Property<string>("Mota")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mota");

                    b.Property<DateTime?>("Ngaycapnhat")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("ngaycapnhat");

                    b.Property<int?>("Soluongton")
                        .HasColumnType("int")
                        .HasColumnName("soluongton");

                    b.Property<string>("Tensp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tensp");

                    b.HasKey("Masp")
                        .HasName("PK__SanPham__7A217672AEC9D6C2");

                    b.HasIndex("IdDanhmuc");

                    b.HasIndex("Idthuvien");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("qlthucung.Models.ThuVienAnh", b =>
                {
                    b.Property<int>("Idthuvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idthuvien")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Img1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("img1");

                    b.Property<string>("Img2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("img2");

                    b.Property<string>("Img3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("img3");

                    b.HasKey("Idthuvien")
                        .HasName("PK__ThuVienA__31FA4CDF3B21DD43");

                    b.ToTable("ThuVienAnh");
                });

            modelBuilder.Entity("qlthucung.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("qlthucung.Models.DonHang", "MadonNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Madon")
                        .HasConstraintName("FK__ChiTietDo__madon__36B12243")
                        .IsRequired();

                    b.HasOne("qlthucung.Models.SanPham", "MaspNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Masp")
                        .HasConstraintName("FK__ChiTietDon__masp__37A5467C")
                        .IsRequired();

                    b.Navigation("MadonNavigation");

                    b.Navigation("MaspNavigation");
                });

            modelBuilder.Entity("qlthucung.Models.DanhGium", b =>
                {
                    b.HasOne("qlthucung.Models.KhachHang", "IdKhNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("IdKh")
                        .HasConstraintName("FK__DanhGia__id_kh__3C69FB99");

                    b.HasOne("qlthucung.Models.SanPham", "IdSpNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("IdSp")
                        .HasConstraintName("FK__DanhGia__id_sp__3B75D760");

                    b.Navigation("IdKhNavigation");

                    b.Navigation("IdSpNavigation");
                });

            modelBuilder.Entity("qlthucung.Models.DichVu", b =>
                {
                    b.HasOne("qlthucung.Models.KhachHang", "MakhNavigation")
                        .WithMany("DichVus")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FK__DichVu__makh__30F848ED");

                    b.Navigation("MakhNavigation");
                });

            modelBuilder.Entity("qlthucung.Models.DonHang", b =>
                {
                    b.HasOne("qlthucung.Models.KhachHang", "MakhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FK__DonHang__makh__33D4B598");

                    b.Navigation("MakhNavigation");
                });

            modelBuilder.Entity("qlthucung.Models.KhachHang", b =>
                {
                    b.HasOne("qlthucung.Models.KhachHangRole", "Role")
                        .WithMany("KhachHangs")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__KhachHang__RoleI__2E1BDC42");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("qlthucung.Models.SanPham", b =>
                {
                    b.HasOne("qlthucung.Models.DanhMuc", "IdDanhmucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDanhmuc")
                        .HasConstraintName("FK__SanPham__idDanhm__286302EC");

                    b.HasOne("qlthucung.Models.ThuVienAnh", "IdthuvienNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("Idthuvien")
                        .HasConstraintName("FK__SanPham__idthuvi__29572725");

                    b.Navigation("IdDanhmucNavigation");

                    b.Navigation("IdthuvienNavigation");
                });

            modelBuilder.Entity("qlthucung.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("qlthucung.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("qlthucung.Models.KhachHang", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DichVus");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("qlthucung.Models.KhachHangRole", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("qlthucung.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("qlthucung.Models.ThuVienAnh", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
